apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-svc
  namespace: default
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80
      name: nginx
      protocol: TCP
      targetPort: 80
      nodePort: 8888