apiVersion: v1
kind: Namespace
metadata:
  name: sit
spec: {}
status: {}
---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
  labels:
    app: redis-pod
spec:
  type: LoadBalancer
  selector:
    app: redis-pod
  ports:
    - name: redis-port
      protocol: TCP
      port: 6380
      nodePort: 6379
      targetPort: 6379
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  namespace: default
  labels:
    controller: deploy
spec:
  replicas: 1
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 300
  selector:
    matchLabels:
      app: redis-pod
    matchExpressions:
      - key: app
        operator: In
        values:
          - redis-pod
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
        - name: redis
          image: redis
          args:
            - "--requirepass 123456"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP
