apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-svc
  namespace: default
  labels:
    app:
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
    - port: 80
      name: nginx
      targetPort: 80